### ISSUE TITLE
Error: Not Implemented: window.computedStyle(elt, pseudoElt)

### ISSUE THREAD

**Issue by amandapouget** [eps1lon/dom-accessibility-api#392]
**Possibly fixed by: https://github.com/eps1lon/dom-accessibility-api/pull/380, not sure**

JSDOM has released an update which no longer allows a second argument to getComputedStyle, as described here:

(first line of changelog 16.4.0 and code changes shown just below that):
https://app.renovatebot.com/package-diff?name=jsdom&from=16.3.0&to=16.4.0

dom-accessibility-api unfortunately calls that function with two arguments

As a result, the console is flooded with warnings like:

```
Error: Not implemented: window.computedStyle(elt, pseudoElt)
          at module.exports (/project_repo/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at getComputedStyle (/project_repo/node_modules/jsdom/lib/jsdom/browser/Window.js:657:7)
          at computeMiscTextAlternative (/project_repo/node_modules/dom-accessibility-api/sources/accessible-name-and-description.ts:332:25)
          at computeTextAlternative (/project_repo/node_modules/dom-accessibility-api/sources/accessible-name-and-description.ts:603:11)
          at computeTextAlternative (/project_repo/node_modules/dom-accessibility-api/sources/accessible-name-and-description.ts:634:3)
          at computeAccessibleName (/project_repo/node_modules/dom-accessibility-api/sources/accessible-name.ts:40:9)
          at /project_repo/node_modules/@testing-library/dom/dist/queries/role.js:110:82
          at Array.filter (<anonymous>)
          at queryAllByRole (/project_repo/node_modules/@testing-library/dom/dist/queries/role.js:104:6)
          at /project_repo/node_modules/@testing-library/dom/dist/query-helpers.js:64:17 undefined
```

You can see the offending lines of code in dom-accessibility-api here:
https://github.com/eps1lon/dom-accessibility-api/blob/main/sources/accessible-name-and-description.ts#L340
https://github.com/eps1lon/dom-accessibility-api/blob/main/sources/accessible-name-and-description.ts#L367

Which would probably be fixed by making a small change to this line:
https://github.com/eps1lon/dom-accessibility-api/blob/main/sources/accessible-name-and-description.ts#L324

Sorry I am not more familiar with this repo or I would take a stab at making the right change.

Versions:
    "@testing-library/dom": "7.21.1",
    ..... using:     "dom-accessibility-api": "0.4.7"

Close if fixed already.

Thank you!

**Comment by eps1lon** [comment]
This is fixed in `dom-accessibility-api@0.5.0`. The [changelog entry](https://github.com/eps1lon/dom-accessibility-api/blob/main/CHANGELOG.md#050) explains how to enable the old behavior which is recommended for environments where `getComputedStyle(element, pseudoElement)` is supported (which is basically every other environment besides `jsdom`).
